// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOmNPTTdO1jTz8I3ENFEwIp2DIjHxBjqM',
    appId: '1:953704517019:web:d1d46c88991bd1c420e53e',
    messagingSenderId: '953704517019',
    projectId: 'flutter-starter-9981e',
    authDomain: 'flutter-starter-9981e.firebaseapp.com',
    storageBucket: 'flutter-starter-9981e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADWZwBckM6Q6DPF3UJKCa_ADcdNhGAqbo',
    appId: '1:953704517019:android:5e8e52aab4ca922b20e53e',
    messagingSenderId: '953704517019',
    projectId: 'flutter-starter-9981e',
    storageBucket: 'flutter-starter-9981e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLQgpvOXqTV2JNYpLk2PkHkljvuCQPNZY',
    appId: '1:953704517019:ios:7d4f1c3da643cd4320e53e',
    messagingSenderId: '953704517019',
    projectId: 'flutter-starter-9981e',
    storageBucket: 'flutter-starter-9981e.appspot.com',
    iosBundleId: 'com.example.firebaseKullanimi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLQgpvOXqTV2JNYpLk2PkHkljvuCQPNZY',
    appId: '1:953704517019:ios:bb0edf036d9fb4ae20e53e',
    messagingSenderId: '953704517019',
    projectId: 'flutter-starter-9981e',
    storageBucket: 'flutter-starter-9981e.appspot.com',
    iosBundleId: 'com.example.firebaseKullanimi.RunnerTests',
  );
}
